services:
  - type: web
    name: transcription-service
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker backend.main:app"
    build:
      apt:
        - build-essential
        - python3-dev
        - libatlas-base-dev
        - gfortran 